### ISSUE TITLE
sudo pip install pgcli not working.

### ISSUE THREAD

**Issue by sandipp** [amjith/pgcli#116]
I got following error while executing `sudo pip install pgcli`

```
Error: pg_config executable not found.



Please add the directory containing pg_config to the PATH

or specify the full executable path with the option:



    python setup.py build_ext --pg-config /path/to/pg_config build ...



or with the pg_config option in 'setup.cfg'.

----------------------------------------

Command python setup.py egg_info failed with error code 1 in /tmp/pip-build-root/psycopg2

Exception information:
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/pip/basecommand.py", line 139, in main
    status = self.run(options, args)
  File "/usr/lib/python2.6/site-packages/pip/commands/install.py", line 266, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python2.6/site-packages/pip/req.py", line 1057, in prepare_files
    req_to_install.run_egg_info()
  File "/usr/lib/python2.6/site-packages/pip/req.py", line 236, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/usr/lib/python2.6/site-packages/pip/util.py", line 662, in call_subprocess
    % (command_desc, proc.returncode, cwd))
InstallationError: Command python setup.py egg_info failed with error code 1 in /tmp/pip-build-root/psycopg2

```

**Comment by amjith** [comment]
One of the requirements for `pgcli` is `psycopg2`. Which requires postgres-dev packages and python-dev packages installed on the system. 

So try one of the following, depending on your linux distro: 

```
$ sudo apt-get install libpq-dev python-dev   # debian

or

$ sudo yum install postgresql-devel python-devel  # redhat
```

and then try `sudo pip install pgcli`.

**Comment by sandipp** [comment]
@amjith `sudo yum install postgresql-devel python-devel  # redhat` this command work perfectly.

Thank you.

**Comment by amjith** [comment]
I'm glad that worked for you. 

Happy hacking!
