### ISSUE TITLE
query errors connecting to a non utf-8 db

### ISSUE THREAD

**Issue by edoardoc** [amjith/pgcli#145]
db> select * FROM table
'ascii' codec can't decode byte 0xc3 in position 104: ordinal not in range(128)

it happens connecting to a us_ascii (non utf-8) encoded db

**Comment by amjith** [comment]
Would you be able to give me an example to reproduce? I'm using psycopg2 for connecting to the postgres database and so far I've seen psycopg2 handle either utf-8 or ascii. So I don't understand how ascii encoding could be failing. 

Can you also send me the log files (they're located in ~/.pgcli.log). 

Thanks

**Comment by edoardoc** [comment]
sending you the logs for now...

**Comment by edoardoc** [comment]
no zip files so here you are:

~ cat ~/.pgcli.log
2015-02-03 11:41:53,146 (33335/MainThread) pgcli.main ERROR - sql: u'select * FROM annuncio400 limit 10', error: UnicodeDecodeError('ascii', 'TAVOLINO come da foto E 5 Spedisco con 9,00 dopo ricarica postepay o bonifico ritiro su Roma uscita del raccordo n\xc2\xb0 17 Torre Angela 1606@live.it                                                                                                                                                                                                                                 ', 114, 115, 'ordinal not in range(128)')
2015-02-03 11:41:53,147 (33335/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/Cellar/pgcli/0.10.2/libexec/lib/python2.7/site-packages/pgcli/main.py", line 106, in cli\n    res = pgexecute.run(document.text)\n  File "/usr/local/Cellar/pgcli/0.10.2/libexec/lib/python2.7/site-packages/pgcli/pgexecute.py", line 120, in run\n    return [(cur.fetchall(), headers, cur.statusmessage)]\nUnicodeDecodeError: \'ascii\' codec can\'t decode byte 0xc2 in position 114: ordinal not in range(128)\n'
2015-02-03 11:41:56,067 (33335/MainThread) pgcli.main ERROR - sql: u'select * FROM annuncio400 limit 10', error: UnicodeDecodeError('ascii', 'TAVOLINO come da foto E 5 Spedisco con 9,00 dopo ricarica postepay o bonifico ritiro su Roma uscita del raccordo n\xc2\xb0 17 Torre Angela 1606@live.it                                                                                                                                                                                                                                 ', 114, 115, 'ordinal not in range(128)')
2015-02-03 11:41:56,068 (33335/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/Cellar/pgcli/0.10.2/libexec/lib/python2.7/site-packages/pgcli/main.py", line 106, in cli\n    res = pgexecute.run(document.text)\n  File "/usr/local/Cellar/pgcli/0.10.2/libexec/lib/python2.7/site-packages/pgcli/pgexecute.py", line 120, in run\n    return [(cur.fetchall(), headers, cur.statusmessage)]\nUnicodeDecodeError: \'ascii\' codec can\'t decode byte 0xc2 in position 114: ordinal not in range(128)\n'
2015-02-03 11:42:13,645 (33335/MainThread) pgcli.main ERROR - sql: u'select * FROM annuncio limit 10', error: UnicodeDecodeError('ascii', "MONTEVERDE Donna Olimpia adiac. Villa Pamphili ottimo punto comm.le locali C/1 vari tagli con possibilit\xc3\xa0 di canna fumaria e ampliamento di pi' vetrine a partire da E 650                                                                                                                                 ", 104, 105, 'ordinal not in range(128)')
2015-02-03 11:42:13,646 (33335/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/Cellar/pgcli/0.10.2/libexec/lib/python2.7/site-packages/pgcli/main.py", line 106, in cli\n    res = pgexecute.run(document.text)\n  File "/usr/local/Cellar/pgcli/0.10.2/libexec/lib/python2.7/site-packages/pgcli/pgexecute.py", line 120, in run\n    return [(cur.fetchall(), headers, cur.statusmessage)]\nUnicodeDecodeError: \'ascii\' codec can\'t decode byte 0xc3 in position 104: ordinal not in range(128)\n'
~

**Comment by amjith** [comment]
Thank you! 

I think it might be a table name with unicode characters. That is a case I have not tested yet. I'll give it a shot.

**Comment by amjith** [comment]
It is now fixed in master. 

You can install directly from github with the following command: 

```
pip install -U -e git+https://github.com/amjith/pgcli.git#egg=pgcli
```

Can you give it a shot and let me know?

**Comment by edoardoc** [comment]
it works :)

**Comment by amjith** [comment]
Yay!! I'll release the new version this weekend. Thank you for testing it.

**Comment by edoardoc** [comment]
it is now showing 

argument 2 to map() must support iteration

every time I hit enter without a command..

**Comment by amjith** [comment]
Good catch. 

I forgot about that case. I've fixed it now. You should be able to run the pip install once more to install from the git repo and it should work as expected.

**Comment by edoardoc** [comment]
yes!
even though it doesn’t harm I’d remove the 

> 
> Command Time: 7.15255737305e-06
> Format Time: 5.96046447754e-06

when you don’t issue any command ...it only reminds you how imprecise the system clock is :)

**Comment by amjith** [comment]
You're right. I should be more clever about this sort of thing. :)

**Comment by edoardoc** [comment]
you are doing a very nice job already.
PS: where could I contribute with a feature request? I was wondering that it would be very nice to have an horizontal scroll view for big tables full of columns.

**Comment by amjith** [comment]
The best place for feature requests is the Github Issues or you can drop in on the gitter chat channel (https://gitter.im/amjith/pgcli) to talk about it. 

Having a horizontal scroll would be impossible in a CLI. I'm not really sure how you could scroll horizontally in CLI. If you have thoughts, I'm eager to hear them. 

Pgcli does support the \x command which is equivalent to psql where the data is displayed in an expanded format. 

Eg:

```
misago_testforum> \x
Expanded display is on.

misago_testforum> SELECT * FROM django_migrations
-[ RECORD 0 ]-----------------------------
id      | 1
app     | misago_acl
name    | 0001_initial
applied | 2014-11-24 14:26:43.153977-08:00
-[ RECORD 1 ]-----------------------------
id      | 2
app     | contenttypes
name    | 0001_initial
applied | 2014-11-24 14:26:43.163630-08:00
```
