### ISSUE TITLE
ImportError on startup in psycopg2 dlopen 

### ISSUE THREAD

**Issue by coil-lighting** [amjith/pgcli#150]
Created a fresh virtualenv (Python 2.7, OS X 64 bit, USC2).
Ran `pip install pgcli`.
Ran `pgcli` from the bash command line, got the following ImportError on dlopen:

(pgcli)~$ pgcli
Traceback (most recent call last):
  File "/Volumes/meta/virtualenvs/pgcli/bin/pgcli", line 9, in <module>
    load_entry_point('pgcli==0.15.4', 'console_scripts', 'pgcli')()
  File "/Volumes/meta/virtualenvs/pgcli/lib/python2.7/site-packages/pkg_resources.py", line 353, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Volumes/meta/virtualenvs/pgcli/lib/python2.7/site-packages/pkg_resources.py", line 2321, in load_entry_point
    return ep.load()
  File "/Volumes/meta/virtualenvs/pgcli/lib/python2.7/site-packages/pkg_resources.py", line 2048, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/Volumes/meta/virtualenvs/pgcli/lib/python2.7/site-packages/pgcli/main.py", line 28, in <module>
    from .pgexecute import PGExecute
  File "/Volumes/meta/virtualenvs/pgcli/lib/python2.7/site-packages/pgcli/pgexecute.py", line 2, in <module>
    import psycopg2
  File "/Volumes/meta/virtualenvs/pgcli/lib/python2.7/site-packages/psycopg2/__init__.py", line 50, in <module>
    from psycopg2._psycopg import BINARY, NUMBER, STRING, DATETIME, ROWID
ImportError: dlopen(/Volumes/meta/virtualenvs/pgcli/lib/python2.7/site-packages/psycopg2/_psycopg.so, 2): Symbol not found: _lo_lseek64
  Referenced from: /Volumes/meta/virtualenvs/pgcli/lib/python2.7/site-packages/psycopg2/_psycopg.so
  Expected in: /usr/lib/libpq.5.dylib
 in /Volumes/meta/virtualenvs/pgcli/lib/python2.7/site-packages/psycopg2/_psycopg.so

I got the same error when I installed pgcli with easy_install in a differeng virtualenv.

**Comment by amjith** [comment]
It looks like the libpq installed on your OS X machine has some linking issues. This is related to psycopg2 installation which is required by pgcli to talk to Postgres database. There are a few possible workarounds covered in the articles below:

http://joshuakehn.com/2013/10/13/Postgresapp-and-psycopg2-on-OS-X.html
http://stackoverflow.com/a/21357519/8825

**Comment by amjith** [comment]
This is the same as #132
