### ISSUE TITLE
Getting an error trying to run

### ISSUE THREAD

**Issue by rpoole** [amjith/pgcli#26]
Whenever I try to use the program I get a python error:

```
Traceback (most recent call last):
  File "/usr/local/bin/pgcli", line 9, in <module>
    load_entry_point('pgcli==0.10.0', 'console_scripts', 'pgcli')()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 610, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 590, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 782, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 416, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pgcli/main.py", line 86, in cli
    refresh_completions(pgexecute, completer)
  File "/usr/local/lib/python2.7/dist-packages/pgcli/main.py", line 176, in refresh_completions
    tables = pgexecute.tables()
  File "/usr/local/lib/python2.7/dist-packages/pgcli/pgexecute.py", line 120, in tables
    with self.conn.cursor() as cur:
AttributeError: __exit__
```

Using python 2.7 and psql 9.3.5 on Ubuntu 14.04.

**Comment by sillypog** [comment]
I get a slightly different error on OSX 10.10, using Python 2.7 and Postgresql 9.2.4.

```
~ $pgcli --help
Traceback (most recent call last):
  File "/usr/local/bin/pgcli", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 2603, in <module>
    working_set.require(__requires__)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 666, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 565, in resolve
    raise DistributionNotFound(req)  # XXX put more info here
pkg_resources.DistributionNotFound: Click
```

**Comment by amjith** [comment]
@rpoole Can you tell me how you're launching pgcli? What are the command line params?

It looks like the database connection is failing. I should report a more sensible error message for that.

**Comment by amjith** [comment]
@sillypog Your error message is because `Click` is not installed. `Click` is a dependency of `pgcli` that should be installed when you do a `pip install pgcli`.

Can you tell me how you installed pgcli?

**Comment by thiagophx** [comment]
Hi @amjith, thanks a lot for this project!
I get the same error as @sillypog, and I did install `pgcli` using `pip`.
Here's the output:

```text
$ pgcli
Traceback (most recent call last):
  File "/usr/local/bin/pgcli", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 2603, in <module>
    working_set.require(__requires__)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 666, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 565, in resolve
    raise DistributionNotFound(req)  # XXX put more info here
pkg_resources.DistributionNotFound: Click

$ pip install pgcli
Requirement already satisfied (use --upgrade to upgrade): pgcli in /Library/Python/2.7/site-packages
Requirement already satisfied (use --upgrade to upgrade): Click in /Library/Python/2.7/site-packages (from pgcli)
Requirement already satisfied (use --upgrade to upgrade): prompt-toolkit in /Library/Python/2.7/site-packages (from pgcli)
Requirement already satisfied (use --upgrade to upgrade): psycopg2 in /Library/Python/2.7/site-packages (from pgcli)
Requirement already satisfied (use --upgrade to upgrade): sqlparse in /Library/Python/2.7/site-packages (from pgcli)
Requirement already satisfied (use --upgrade to upgrade): docopt in /Library/Python/2.7/site-packages (from prompt-toolkit->pgcli)
Requirement already satisfied (use --upgrade to upgrade): jedi>=0.8.1 in /Library/Python/2.7/site-packages (from prompt-toolkit->pgcli)
Requirement already satisfied (use --upgrade to upgrade): pygments in /Library/Python/2.7/site-packages (from prompt-toolkit->pgcli)
Requirement already satisfied (use --upgrade to upgrade): six>=1.8.0 in /Library/Python/2.7/site-packages (from prompt-toolkit->pgcli)
Requirement already satisfied (use --upgrade to upgrade): wcwidth in /Library/Python/2.7/site-packages (from prompt-toolkit->pgcli)
Cleaning up...

$ which python
/usr/bin/python

$ pip freeze | grep 'click\|pgcli'
click==3.3
pgcli==0.10.0
```

It seems that `pgcli` and `click` were installed successfully, but it still doesn't work.
Any idea why?

Thanks in advance.

**Comment by amjith** [comment]
@sillypog @thiagophx Let's track this issue on #27. The original issue reported by @rpoole seems unrelated to the ones you guys are facing.

**Comment by cezio** [comment]
@rpoole Which psycopg version you're using? Context Manager support in cursor was added in 2.5 http://pythonhosted.org//psycopg2/news.html#what-s-new-in-psycopg-2-5

**Comment by rpoole** [comment]
@cezio that was it! I had an old version of psycopg2 (2.4.5).

Thanks for the help and the hard work on the tool - it looks great!

**Comment by amjith** [comment]
Version 0.10.1 released to PyPI. https://pypi.python.org/pypi/pgcli/0.10.1
