### ISSUE TITLE
More graceful error management

### ISSUE THREAD

**Issue by svenstaro** [amjith/pgcli#32]
Currently, on syntax errors in psycopg2 and connection error, the error isn't caught and pgcli fails and exits. Perhaps you should handle that more gracefully.

**Comment by amjith** [comment]
Can you give me a sample error that you're getting?

I tried `pgcli non-existent-db` and I get a `FATAL:  database "abc" does not exist`. 

I presume you're triggering a different scenario. If you can tell me how you're triggering the error that'll be useful as well.

**Comment by Walms** [comment]
Syntax errors in the sql will cause an exit for me. 

For instance if my sql is just 'SELECT' I get :

    amorini> SELECT                        
    Traceback (most recent call last):
      File "/usr/local/lib/python3.3/dist-packages/pgcli/packages/pgspecial.py", line 746, in execute
        command_executor = CASE_SENSITIVE_COMMANDS[command][0]
    KeyError: 'SELECT'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/usr/local/lib/python3.3/dist-packages/pgcli/pgexecute.py", line 105, in run
        return pgspecial.execute(cur, sql)
      File "/usr/local/lib/python3.3/dist-packages/pgcli/packages/pgspecial.py", line 748, in execute
        command_executor = NON_CASE_SENSITIVE_COMMANDS[command.lower()][0]
    KeyError: 'select'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/usr/local/lib/python3.3/dist-packages/pgcli/main.py", line 104, in cli
        res = pgexecute.run(document.text)
      File "/usr/local/lib/python3.3/dist-packages/pgcli/pgexecute.py", line 108, in run
        cur.execute(sql)
    psycopg2.ProgrammingError: syntax error at end of input
    LINE 1: SELECT
                  ^


    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/usr/local/bin/pgcli", line 9, in <module>
        load_entry_point('pgcli==0.10.0', 'console_scripts', 'pgcli')()
      File "/usr/local/lib/python3.3/dist-packages/click/core.py", line 610, in __call__
        return self.main(*args, **kwargs)
      File "/usr/local/lib/python3.3/dist-packages/click/core.py", line 590, in main
        rv = self.invoke(ctx)
      File "/usr/local/lib/python3.3/dist-packages/click/core.py", line 782, in invoke
        return ctx.invoke(self.callback, **ctx.params)
      File "/usr/local/lib/python3.3/dist-packages/click/core.py", line 416, in invoke
        return callback(*args, **kwargs)
      File "/usr/local/lib/python3.3/dist-packages/pgcli/main.py", line 116, in cli
        _logger.debug("sql: %r, error: %r", document.text, e.message)
    AttributeError: 'ProgrammingError' object has no attribute 'message'

**Comment by Walms** [comment]
In main.py 

Chaning e.message to e.pgerror seems to fix it.
115             except Exception as e:
116                 _logger.debug("sql: %r, error: %r", document.text, e.pgerror)
117                 click.secho(e.pgerror, err=True, fg='red')


http://initd.org/psycopg/docs/module.html#psycopg2.Error psycopg2 errros don't seem to have a message prop. This may be something that is different across version.

**Comment by wangyandong-ningxia** [comment]
I've got similar errors under Python 3.4.2
```
» python --version                                                                                                  
Python 3.4.2
```
```
» pgcli
Traceback (most recent call last):
  File "/Users/wangyandong/.pyenv/versions/3.4.2/lib/python3.4/site-packages/pgcli/main.py", line 73, in cli
    pgexecute = PGExecute(database, user, passwd, host, port)
  File "/Users/wangyandong/.pyenv/versions/3.4.2/lib/python3.4/site-packages/pgcli/pgexecute.py", line 68, in __init__
    password=self.password, host=self.host, port=self.port)
  File "/Users/wangyandong/.pyenv/versions/3.4.2/lib/python3.4/site-packages/psycopg2/__init__.py", line 164, in connect
    conn = _connect(dsn, connection_factory=connection_factory, async=async)
psycopg2.OperationalError: FATAL:  database "wangyandong" does not exist


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/wangyandong/.pyenv/versions/3.4.2/bin/pgcli", line 9, in <module>
    load_entry_point('pgcli==0.10.0', 'console_scripts', 'pgcli')()
  File "/Users/wangyandong/.pyenv/versions/3.4.2/lib/python3.4/site-packages/click/core.py", line 610, in __call__
    return self.main(*args, **kwargs)
  File "/Users/wangyandong/.pyenv/versions/3.4.2/lib/python3.4/site-packages/click/core.py", line 590, in main
    rv = self.invoke(ctx)
  File "/Users/wangyandong/.pyenv/versions/3.4.2/lib/python3.4/site-packages/click/core.py", line 782, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/wangyandong/.pyenv/versions/3.4.2/lib/python3.4/site-packages/click/core.py", line 416, in invoke
    return callback(*args, **kwargs)
  File "/Users/wangyandong/.pyenv/versions/3.4.2/lib/python3.4/site-packages/pgcli/main.py", line 75, in cli
    _logger.debug('Database connection failed: %r.', e.message)
AttributeError: 'OperationalError' object has no attribute 'message'
```
```
» pgcli djangodb                                                                                                    
djangodb> SELECT
Traceback (most recent call last):
  File "/Users/wangyandong/.pyenv/versions/3.4.2/lib/python3.4/site-packages/pgcli/packages/pgspecial.py", line 746, in execute
    command_executor = CASE_SENSITIVE_COMMANDS[command][0]
KeyError: 'SELECT'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/wangyandong/.pyenv/versions/3.4.2/lib/python3.4/site-packages/pgcli/pgexecute.py", line 105, in run
    return pgspecial.execute(cur, sql)
  File "/Users/wangyandong/.pyenv/versions/3.4.2/lib/python3.4/site-packages/pgcli/packages/pgspecial.py", line 748, in execute
    command_executor = NON_CASE_SENSITIVE_COMMANDS[command.lower()][0]
KeyError: 'select'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/wangyandong/.pyenv/versions/3.4.2/lib/python3.4/site-packages/pgcli/main.py", line 104, in cli
    res = pgexecute.run(document.text)
  File "/Users/wangyandong/.pyenv/versions/3.4.2/lib/python3.4/site-packages/pgcli/pgexecute.py", line 108, in run
    cur.execute(sql)
psycopg2.ProgrammingError: syntax error at end of input
LINE 1: SELECT
              ^


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/wangyandong/.pyenv/versions/3.4.2/bin/pgcli", line 9, in <module>
    load_entry_point('pgcli==0.10.0', 'console_scripts', 'pgcli')()
  File "/Users/wangyandong/.pyenv/versions/3.4.2/lib/python3.4/site-packages/click/core.py", line 610, in __call__
    return self.main(*args, **kwargs)
  File "/Users/wangyandong/.pyenv/versions/3.4.2/lib/python3.4/site-packages/click/core.py", line 590, in main
    rv = self.invoke(ctx)
  File "/Users/wangyandong/.pyenv/versions/3.4.2/lib/python3.4/site-packages/click/core.py", line 782, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/wangyandong/.pyenv/versions/3.4.2/lib/python3.4/site-packages/click/core.py", line 416, in invoke
    return callback(*args, **kwargs)
  File "/Users/wangyandong/.pyenv/versions/3.4.2/lib/python3.4/site-packages/pgcli/main.py", line 116, in cli
    _logger.debug("sql: %r, error: %r", document.text, e.message)
AttributeError: 'ProgrammingError' object has no attribute 'message'
```
It works fine under Python 2.7.8

**Comment by amjith** [comment]
PR #49 and #50 fix this issue. It will be released in the next ver. 

Thank you for reporting.

**Comment by amjith** [comment]
Version 0.10.1 released to PyPI. https://pypi.python.org/pypi/pgcli/0.10.1
