### ISSUE TITLE
ImportError: No module named sql

### ISSUE THREAD

**Issue by vapniks** [amjith/pgcli#33]
Here is the error I get when I try to run it on Ubuntu 12.04:

Traceback (most recent call last):
  File "/usr/local/bin/pgcli", line 9, in <module>
    load_entry_point('pgcli==0.10.0', 'console_scripts', 'pgcli')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 337, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2279, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1989, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/usr/local/lib/python2.7/dist-packages/pgcli/main.py", line 16, in <module>
    from pygments.lexers.sql import SqlLexer
ImportError: No module named sql

**Comment by vapniks** [comment]
Yes, that fixed it thanks.
